"""
200 SEO keywords for ZenskoZdravlje.ba grouped into topical clusters.
Each cluster has 1 pillar (is_pillar=True) and supporting articles.
Language: Bosnian (Latin script)
"""

CLUSTERS = [
    # --- CLUSTER 1: PCOS ---
    {
        'cluster': 'pcos',
        'posts': [
            {'keyword': 'PCOS: simptomi, uzroci, dijagnoza i lijecenje', 'is_pillar': True,
             'slug': 'pcos-simptomi-uzroci-dijagnoza-lijecenje'},
            {'keyword': 'Kako se postavlja dijagnoza PCOS-a', 'is_pillar': False,
             'slug': 'dijagnoza-pcos-kako-se-postavlja'},
            {'keyword': 'PCOS i inzulinska rezistencija: veza i lijecenje', 'is_pillar': False,
             'slug': 'pcos-inzulinska-rezistencija'},
            {'keyword': 'PCOS i plodnost: mozete li zatrudnjeti', 'is_pillar': False,
             'slug': 'pcos-plodnost-trudnoca'},
            {'keyword': 'Prirodni tretmani za PCOS bez lijekova', 'is_pillar': False,
             'slug': 'prirodni-tretmani-pcos'},
            {'keyword': 'Dijeta za PCOS: koja hrana pomaze i koja steti', 'is_pillar': False,
             'slug': 'dijeta-pcos-ishrana'},
            {'keyword': 'Suplementi za PCOS: myo-inositol, magnezij i vitamin D', 'is_pillar': False,
             'slug': 'suplementi-pcos'},
            {'keyword': 'PCOS i izostanak menstruacije: uzroci i rjesenja', 'is_pillar': False,
             'slug': 'pcos-izostanak-menstruacije'},
            {'keyword': 'Visok testosteron kod zena: simptomi i lijecenje', 'is_pillar': False,
             'slug': 'visok-testosteron-zene-simptomi'},
            {'keyword': 'PCOS i akne: hormonska veza i tretman', 'is_pillar': False,
             'slug': 'pcos-akne-hormonska-veza'},
            {'keyword': 'PCOS i debljanje: zasto je tesko smrsati', 'is_pillar': False,
             'slug': 'pcos-debljanje-smrsati'},
            {'keyword': 'Inositol za PCOS: istrazivanja i doziranje', 'is_pillar': False,
             'slug': 'inositol-pcos-istrazivanja-doziranje'},
            {'keyword': 'PCOS i stres: uloga kortizola', 'is_pillar': False,
             'slug': 'pcos-stres-kortizol'},
            {'keyword': 'LH i FSH hormoni kod PCOS-a: sta znace rezultati', 'is_pillar': False,
             'slug': 'lh-fsh-hormoni-pcos-rezultati'},
            {'keyword': 'PCOS kod tinejdzerica: znaci i lijecenje', 'is_pillar': False,
             'slug': 'pcos-tinejdzerice-adolescentice'},
            {'keyword': 'Metformin za PCOS: kako funkcionira', 'is_pillar': False,
             'slug': 'metformin-pcos-lijecenje'},
            {'keyword': 'PCOS i gubitak kose: androgena alopecija kod zena', 'is_pillar': False,
             'slug': 'pcos-gubitak-kose-alopecija'},
            {'keyword': 'Spavanje i PCOS: utjecaj na hormone', 'is_pillar': False,
             'slug': 'spavanje-pcos-hormoni'},
            {'keyword': 'PCOS i tjelovjezbanje: koji sport pomaze', 'is_pillar': False,
             'slug': 'pcos-tjelovjezbanje-vjezbanje'},
            {'keyword': 'Zivot s PCOS-om: svakodnevne strategije', 'is_pillar': False,
             'slug': 'zivot-s-pcos-strategije'},
        ],
    },

    # --- CLUSTER 2: Menstrualni ciklus ---
    {
        'cluster': 'menstrualni-ciklus',
        'posts': [
            {'keyword': 'Menstrualni ciklus: kompletan vodic kroz sve faze', 'is_pillar': True,
             'slug': 'menstrualni-ciklus-kompletan-vodic'},
            {'keyword': 'Normalna menstruacija: sta je normalno a sta nije', 'is_pillar': False,
             'slug': 'normalna-menstruacija-sta-je-normalno'},
            {'keyword': 'Faze menstrualnog ciklusa i hormonalne promjene', 'is_pillar': False,
             'slug': 'faze-menstrualnog-ciklusa-hormoni'},
            {'keyword': 'Ovulacija: kada se desava i kako je prepoznati', 'is_pillar': False,
             'slug': 'ovulacija-kada-se-desava-prepoznati'},
            {'keyword': 'PMS simptomi: uzroci i prirodno olaksanje', 'is_pillar': False,
             'slug': 'pms-simptomi-uzroci-olaksanje'},
            {'keyword': 'Bolna menstruacija: uzroci i nacini olaksanja', 'is_pillar': False,
             'slug': 'bolna-menstruacija-uzroci-olaksanje'},
            {'keyword': 'Neredovita menstruacija: uzroci i kada posjetiti ginekologa', 'is_pillar': False,
             'slug': 'neredovita-menstruacija-uzroci'},
            {'keyword': 'Obilna menstruacija: uzroci, simptomi i lijecenje', 'is_pillar': False,
             'slug': 'obilna-menstruacija-uzroci-lijecenje'},
            {'keyword': 'Izostanak menstruacije bez trudnoce: 10 uzroka', 'is_pillar': False,
             'slug': 'izostanak-menstruacije-bez-trudnoce'},
            {'keyword': 'Pracenje bazalne tjelesne temperature za ovulaciju', 'is_pillar': False,
             'slug': 'bazalna-tjelesna-temperatura-ovulacija'},
            {'keyword': 'Menstruacija i ishrana: hrana koja pomaze', 'is_pillar': False,
             'slug': 'menstruacija-ishrana-hrana'},
            {'keyword': 'Hormonska kontracepcija i menstrualni ciklus', 'is_pillar': False,
             'slug': 'hormonska-kontracepcija-menstrualni-ciklus'},
            {'keyword': 'Lutealna faza: simptomi i problemi', 'is_pillar': False,
             'slug': 'lutealna-faza-simptomi-problemi'},
            {'keyword': 'Folikularna faza: sta se desava u tijelu', 'is_pillar': False,
             'slug': 'folikularna-faza-tijelo'},
            {'keyword': 'Spotting izmedju ciklusa: uzroci i kada brinuti', 'is_pillar': False,
             'slug': 'spotting-krvarenje-izmedju-ciklusa'},
            {'keyword': 'Fizicka aktivnost i menstrualni ciklus', 'is_pillar': False,
             'slug': 'fizicka-aktivnost-menstrualni-ciklus'},
            {'keyword': 'Amenoreja: izostanak menstruacije duze od 3 mjeseca', 'is_pillar': False,
             'slug': 'amenoreja-izostanak-menstruacije'},
            {'keyword': 'Menstrualni bolovi u ledjima: uzroci i olaksanje', 'is_pillar': False,
             'slug': 'menstrualni-bolovi-ledja'},
            {'keyword': 'Aplikacije za pracenje menstrualnog ciklusa', 'is_pillar': False,
             'slug': 'aplikacije-pracenje-ciklusa'},
            {'keyword': 'Menopauza: simptomi, faze i kako se nositi', 'is_pillar': False,
             'slug': 'menopauza-simptomi-faze'},
        ],
    },

    # --- CLUSTER 3: Ginekolosko zdravlje ---
    {
        'cluster': 'ginekolosko-zdravlje',
        'posts': [
            {'keyword': 'Ginekolosko zdravlje: kompletan vodic za zene', 'is_pillar': True,
             'slug': 'ginekolosko-zdravlje-kompletan-vodic'},
            {'keyword': 'Kada posjetiti ginekologa: znaci koje ne smijete ignorisati', 'is_pillar': False,
             'slug': 'kada-posjetiti-ginekologa'},
            {'keyword': 'Endometrioza: simptomi, dijagnoza i lijecenje', 'is_pillar': False,
             'slug': 'endometrioza-simptomi-dijagnoza-lijecenje'},
            {'keyword': 'Miomi materice: sta su i kako se lijece', 'is_pillar': False,
             'slug': 'miomi-materice-lijecenje'},
            {'keyword': 'Ovarijalne ciste: vrste, simptomi i lijecenje', 'is_pillar': False,
             'slug': 'ovarijalne-ciste-vrste-lijecenje'},
            {'keyword': 'Vaginalna infekcija: uzroci, simptomi i lijecenje', 'is_pillar': False,
             'slug': 'vaginalna-infekcija-simptomi-lijecenje'},
            {'keyword': 'Kandidijaza: gljicna infekcija vagine', 'is_pillar': False,
             'slug': 'kandidijaza-gljicna-infekcija-vagine'},
            {'keyword': 'Bakterijska vaginoza: uzroci i lijecenje', 'is_pillar': False,
             'slug': 'bakterijska-vaginoza-uzroci-lijecenje'},
            {'keyword': 'Brisevi kod ginekologa: sta sve testiraju', 'is_pillar': False,
             'slug': 'brisevi-ginekolog-testovi'},
            {'keyword': 'Papa test: sta je i koliko cesto raditi', 'is_pillar': False,
             'slug': 'papa-test-sto-je-koliko-cesto'},
            {'keyword': 'HPV virus: sta trebate znati', 'is_pillar': False,
             'slug': 'hpv-virus-sto-trebate-znati'},
            {'keyword': 'Adneksitis: upala jajovoda i jajnika', 'is_pillar': False,
             'slug': 'adneksitis-upala-jajovoda-jajnika'},
            {'keyword': 'Vulvodynija: bol vulve uzroci i lijecenje', 'is_pillar': False,
             'slug': 'vulvodynija-bol-vulve'},
            {'keyword': 'Adenomioza: simptomi i razlika od endometrioze', 'is_pillar': False,
             'slug': 'adenomioza-simptomi-razlika'},
            {'keyword': 'Ultrazvuk zdjelice: kada i zasto se radi', 'is_pillar': False,
             'slug': 'ultrazvuk-zdjelice-kada-zasto'},
            {'keyword': 'Kolposkopija: sta je i kako se priprema', 'is_pillar': False,
             'slug': 'kolposkopija-priprema-postupak'},
            {'keyword': 'Polip materice: simptomi i lijecenje', 'is_pillar': False,
             'slug': 'polip-materice-simptomi-lijecenje'},
            {'keyword': 'Inkontinencija urina kod zena: uzroci i rjesenja', 'is_pillar': False,
             'slug': 'inkontinencija-urina-zene'},
            {'keyword': 'Vaginalni iscjedak: sta je normalno a sta ne', 'is_pillar': False,
             'slug': 'vaginalni-iscjedak-normalan-abnormalan'},
            {'keyword': 'Rak grlica materice: prevencija i rani simptomi', 'is_pillar': False,
             'slug': 'rak-grlica-materice-prevencija'},
        ],
    },

    # --- CLUSTER 4: Trudnoca i plodnost ---
    {
        'cluster': 'trudnoca-plodnost',
        'posts': [
            {'keyword': 'Plodnost kod zena: sve sto trebate znati', 'is_pillar': True,
             'slug': 'plodnost-zene-kompletan-vodic'},
            {'keyword': 'Kako povecati sanse za trudnocu prirodno', 'is_pillar': False,
             'slug': 'povecati-sanse-trudnoca-prirodno'},
            {'keyword': 'Neplodnost kod zena: uzroci i opcije lijecenja', 'is_pillar': False,
             'slug': 'neplodnost-zene-uzroci-lijecenje'},
            {'keyword': 'Rani znaci trudnoce: simptomi prvog tromjesecja', 'is_pillar': False,
             'slug': 'rani-znaci-trudnoce-simptomi'},
            {'keyword': 'Prirodni nacini poboljsanja plodnosti', 'is_pillar': False,
             'slug': 'prirodni-nacini-poboljsanje-plodnosti'},
            {'keyword': 'Folna kiselina u trudnoci: zasto je vazna', 'is_pillar': False,
             'slug': 'folna-kiselina-trudnoca-vaznost'},
            {'keyword': 'IVF: vantjelesna oplodnja - sto se desava', 'is_pillar': False,
             'slug': 'ivf-vantjelesna-oplodnja-postupak'},
            {'keyword': 'Spontani pobacaj: uzroci i emocionalni oporavak', 'is_pillar': False,
             'slug': 'spontani-pobacaj-uzroci-oporavak'},
            {'keyword': 'Trudnoca nakon 35: sto trebate znati', 'is_pillar': False,
             'slug': 'trudnoca-nakon-35-sto-znati'},
            {'keyword': 'Prenatalni vitamini: koji su najvazni', 'is_pillar': False,
             'slug': 'prenatalni-vitamini-najvazniji'},
            {'keyword': 'Tjelesna tezina i plodnost: koliko utjece', 'is_pillar': False,
             'slug': 'tjelesna-tezina-plodnost'},
            {'keyword': 'Stres i plodnost: kako stres utjece na trudnocu', 'is_pillar': False,
             'slug': 'stres-plodnost-trudnoca'},
            {'keyword': 'Dojenje i menstrualni ciklus: sta ocekivati', 'is_pillar': False,
             'slug': 'dojenje-menstrualni-ciklus'},
            {'keyword': 'PCOS i trudnoca: moguce komplikacije i zastita', 'is_pillar': False,
             'slug': 'pcos-trudnoca-komplikacije'},
            {'keyword': 'Tireoidna zliezda i trudnoca: hipotireoza i plodnost', 'is_pillar': False,
             'slug': 'tireoidna-zliezda-trudnoca-plodnost'},
            {'keyword': 'Koenzim Q10 za plodnost: sta kaze nauka', 'is_pillar': False,
             'slug': 'koenzim-q10-plodnost-nauka'},
            {'keyword': 'Hormonski testovi za plodnost: AMH, FSH, LH', 'is_pillar': False,
             'slug': 'hormonski-testovi-plodnost-amh-fsh'},
            {'keyword': 'Trudnoca i dijabetes: gestacijski dijabetes', 'is_pillar': False,
             'slug': 'gestacijski-dijabetes-trudnoca'},
            {'keyword': 'Sekundarna neplodnost: uzroci kada niste mogli zatrudnjeti drugi put', 'is_pillar': False,
             'slug': 'sekundarna-neplodnost-uzroci'},
            {'keyword': 'Zamrznuta jajasca: fertilizacija i opcije', 'is_pillar': False,
             'slug': 'zamrznuta-jajasca-fertilizacija'},
        ],
    },

    # --- CLUSTER 5: Ishrana za zensko zdravlje ---
    {
        'cluster': 'ishrana-zensko-zdravlje',
        'posts': [
            {'keyword': 'Ishrana za zensko zdravlje: kompletan nutritivni vodic', 'is_pillar': True,
             'slug': 'ishrana-zensko-zdravlje-vodic'},
            {'keyword': 'Namirnice koje balansiraju hormone kod zena', 'is_pillar': False,
             'slug': 'namirnice-balansiraj-hormone-zene'},
            {'keyword': 'Anti-upalna ishrana za zene s PCOS-om i endometriozom', 'is_pillar': False,
             'slug': 'anti-upalna-ishrana-pcos-endometrioza'},
            {'keyword': 'Gvozdje u ishrani zena: nedostatak i prirodni izvori', 'is_pillar': False,
             'slug': 'gvozdje-ishrana-zena-nedostatak'},
            {'keyword': 'Kalcij i kosti kod zena: koliko je dovoljno', 'is_pillar': False,
             'slug': 'kalcij-kosti-zene-doza'},
            {'keyword': 'Omega-3 masne kiseline za zensko zdravlje', 'is_pillar': False,
             'slug': 'omega-3-masne-kiseline-zensko-zdravlje'},
            {'keyword': 'Magnezij za zene: prednosti i uzimanje', 'is_pillar': False,
             'slug': 'magnezij-zene-prednosti-uzimanje'},
            {'keyword': 'Ishrana u menopauzi: sto jesti za bolji zivot', 'is_pillar': False,
             'slug': 'ishrana-menopauza-sto-jesti'},
            {'keyword': 'Ishrana u menstruaciji: hrana za olaksanje boli', 'is_pillar': False,
             'slug': 'ishrana-menstruacija-olaksanje'},
            {'keyword': 'Postenje i zenski hormoni: intermitentni post', 'is_pillar': False,
             'slug': 'postenje-zenski-hormoni-intermitentni'},
            {'keyword': 'Fitoestrogeni u hrani: soja, lan i hormoni', 'is_pillar': False,
             'slug': 'fitoestrogeni-hrana-soja-lan'},
            {'keyword': 'Probiotici za zensko zdravlje: crijeva i hormoni', 'is_pillar': False,
             'slug': 'probiotici-zensko-zdravlje-crijeva'},
            {'keyword': 'Secer i zenski hormoni: utjecaj na ciklus', 'is_pillar': False,
             'slug': 'secer-zenski-hormoni-ciklus'},
            {'keyword': 'Proteini za zene: koliko je dovoljno', 'is_pillar': False,
             'slug': 'proteini-zene-koliko-dovoljno'},
            {'keyword': 'Hidratacija i zensko zdravlje: koliko vode piti', 'is_pillar': False,
             'slug': 'hidratacija-zensko-zdravlje-voda'},
            {'keyword': 'Alkohol i zenski hormoni: utjecaj na ciklus', 'is_pillar': False,
             'slug': 'alkohol-zenski-hormoni-utjecaj'},
            {'keyword': 'Kofein i menstrualni ciklus: sto kaze nauka', 'is_pillar': False,
             'slug': 'kofein-menstrualni-ciklus-nauka'},
            {'keyword': 'Gluten i zensko zdravlje: da li utjece na hormone', 'is_pillar': False,
             'slug': 'gluten-zensko-zdravlje-hormoni'},
            {'keyword': 'Hrana bogata zeljezom za anemicne zene', 'is_pillar': False,
             'slug': 'hrana-bogata-zeljezom-anemija'},
            {'keyword': 'Veganska ishrana i zenski hormoni', 'is_pillar': False,
             'slug': 'veganska-ishrana-zenski-hormoni'},
        ],
    },

    # --- CLUSTER 6: Vitamini i suplementi ---
    {
        'cluster': 'vitamini-suplementi',
        'posts': [
            {'keyword': 'Vitamini i suplementi za zensko zdravlje: kompletan vodic', 'is_pillar': True,
             'slug': 'vitamini-suplementi-zensko-zdravlje-vodic'},
            {'keyword': 'Vitamin D i zensko zdravlje: nedostatak i simptomi', 'is_pillar': False,
             'slug': 'vitamin-d-zensko-zdravlje-nedostatak'},
            {'keyword': 'Folna kiselina: doza i vaznost za zene', 'is_pillar': False,
             'slug': 'folna-kiselina-doza-vaznost'},
            {'keyword': 'Vitamin B12 za zene: simptomi nedostatka', 'is_pillar': False,
             'slug': 'vitamin-b12-zene-simptomi-nedostatka'},
            {'keyword': 'Zeljezni suplementi: kada i kako uzimati', 'is_pillar': False,
             'slug': 'zeljezni-suplementi-kada-uzimati'},
            {'keyword': 'Magnezij za PMS i menstrualne bolove', 'is_pillar': False,
             'slug': 'magnezij-pms-menstrualni-bolovi'},
            {'keyword': 'Cink i zenski reproduktivni sistem', 'is_pillar': False,
             'slug': 'cink-zenski-reproduktivni-sistem'},
            {'keyword': 'Omega-3 suplementi: koji su najbolji za zene', 'is_pillar': False,
             'slug': 'omega-3-suplementi-zene-koji-odabrati'},
            {'keyword': 'Probiotici za vaginalnu floru i imunitet', 'is_pillar': False,
             'slug': 'probiotici-vaginalna-flora-imunitet'},
            {'keyword': 'Vitamin C i zeljezo: apsorpcija i imunitet', 'is_pillar': False,
             'slug': 'vitamin-c-zeljezo-apsorpcija'},
            {'keyword': 'Kolagen za zene: prednosti za kozu i zglobove', 'is_pillar': False,
             'slug': 'kolagen-zene-prednosti-koza-zglobovi'},
            {'keyword': 'Ashwagandha za zene: stres, hormoni i plodnost', 'is_pillar': False,
             'slug': 'ashwagandha-zene-stres-hormoni'},
            {'keyword': 'Vitex (konopljika) za regulaciju ciklusa', 'is_pillar': False,
             'slug': 'vitex-konopljika-regulacija-ciklusa'},
            {'keyword': 'NAC (N-acetil cistein) za PCOS i plodnost', 'is_pillar': False,
             'slug': 'nac-n-acetil-cistein-pcos'},
            {'keyword': 'Berberina za inzulinsku rezistenciju i PCOS', 'is_pillar': False,
             'slug': 'berberina-inzulinska-rezistencija-pcos'},
            {'keyword': 'Vitamin E za zensko zdravlje i plodnost', 'is_pillar': False,
             'slug': 'vitamin-e-zensko-zdravlje-plodnost'},
            {'keyword': 'Zeleni cajevi i biljni lijekovi za zensko zdravlje', 'is_pillar': False,
             'slug': 'zeleni-cajevi-biljni-lijekovi-zensko'},
            {'keyword': 'Kalcij i vitamin D za zdrave kosti kod zena', 'is_pillar': False,
             'slug': 'kalcij-vitamin-d-kosti-zene'},
            {'keyword': 'Maca prah za zenski libido i energiju', 'is_pillar': False,
             'slug': 'maca-prah-libido-energija-zene'},
            {'keyword': 'Iodine (jod) i tireoidna zliezda kod zena', 'is_pillar': False,
             'slug': 'jod-tireoidna-zliezda-zene'},
        ],
    },

    # --- CLUSTER 7: Mentalno zdravlje ---
    {
        'cluster': 'mentalno-zdravlje',
        'posts': [
            {'keyword': 'Mentalno zdravlje zena: hormoni, emocije i briga o sebi', 'is_pillar': True,
             'slug': 'mentalno-zdravlje-zena-vodic'},
            {'keyword': 'Anksioznost kod zena: uzroci i prirodne tehnike', 'is_pillar': False,
             'slug': 'anksioznost-zene-uzroci-tehnike'},
            {'keyword': 'Depresija kod zena: simptomi i kada potraziti pomoc', 'is_pillar': False,
             'slug': 'depresija-zene-simptomi-pomoc'},
            {'keyword': 'Hormoni i raspolozenje: estrogen, progesteron i serotonin', 'is_pillar': False,
             'slug': 'hormoni-raspolozenje-estrogen-serotonin'},
            {'keyword': 'Postpartalna depresija: simptomi i lijecenje', 'is_pillar': False,
             'slug': 'postpartalna-depresija-simptomi'},
            {'keyword': 'Perimenopauza i mentalno zdravlje', 'is_pillar': False,
             'slug': 'perimenopauza-mentalno-zdravlje'},
            {'keyword': 'PMDD: teski premenstrualni sindrom', 'is_pillar': False,
             'slug': 'pmdd-teski-premenstrualni-sindrom'},
            {'keyword': 'Burnout kod zena: simptomi i oporavak', 'is_pillar': False,
             'slug': 'burnout-zene-simptomi-oporavak'},
            {'keyword': 'Mindfulness i meditacija za hormonsku ravnotezu', 'is_pillar': False,
             'slug': 'mindfulness-meditacija-hormonska-ravnoteza'},
            {'keyword': 'Poremecaj slike tijela i zensko zdravlje', 'is_pillar': False,
             'slug': 'slika-tijela-zensko-zdravlje'},
            {'keyword': 'Spavanje i zenski hormoni: koliko sna trebamo', 'is_pillar': False,
             'slug': 'spavanje-zenski-hormoni-koliko-sna'},
            {'keyword': 'Kortizol i stres kod zena: kako smanjiti', 'is_pillar': False,
             'slug': 'kortizol-stres-zene-smanjiti'},
            {'keyword': 'Veze i mentalno zdravlje: toksicne veze i samopouzdanje', 'is_pillar': False,
             'slug': 'veze-mentalno-zdravlje-toksicne'},
            {'keyword': 'Hranidba i mentalno zdravlje: crijevno-mozdana os', 'is_pillar': False,
             'slug': 'hranidba-mentalno-zdravlje-crijeva-mozak'},
            {'keyword': 'Vjezba kao terapija za anksioznost i depresiju', 'is_pillar': False,
             'slug': 'vjezba-terapija-anksioznost-depresija'},
            {'keyword': 'Emocionalno jedenje kod zena: uzroci i strategije', 'is_pillar': False,
             'slug': 'emocionalno-jedenje-zene-strategije'},
            {'keyword': 'Trauma i zensko tijelo: fizicki efekti', 'is_pillar': False,
             'slug': 'trauma-zensko-tijelo-fizicki-efekti'},
            {'keyword': 'Terapija razgovorom: kada i kako potraziti psihologa', 'is_pillar': False,
             'slug': 'terapija-razgovorom-psiholog-kada'},
            {'keyword': 'Sezonska depresija kod zena: SAD i zimski period', 'is_pillar': False,
             'slug': 'sezonska-depresija-zene-sad-zima'},
            {'keyword': 'Samopouzdanje i hormonalni ciklus', 'is_pillar': False,
             'slug': 'samopouzdanje-hormonalni-ciklus'},
        ],
    },

    # --- CLUSTER 8: Koza, kosa i hormoni ---
    {
        'cluster': 'koza-kosa-hormoni',
        'posts': [
            {'keyword': 'Koza i hormoni: kompletan vodic za zensku kozu', 'is_pillar': True,
             'slug': 'koza-hormoni-zenski-vodic'},
            {'keyword': 'Hormonalne akne kod zena: uzroci i tretmani', 'is_pillar': False,
             'slug': 'hormonalne-akne-uzroci-tretmani'},
            {'keyword': 'Gubitak kose kod zena: uzroci i rjesenja', 'is_pillar': False,
             'slug': 'gubitak-kose-zene-uzroci-rjesenja'},
            {'keyword': 'Suha koza i hormoni: povezanost i njega', 'is_pillar': False,
             'slug': 'suha-koza-hormoni-njega'},
            {'keyword': 'Ekcem i hormonalni disbalans', 'is_pillar': False,
             'slug': 'ekcem-hormonalni-disbalans'},
            {'keyword': 'Hirzutizam: prekomjerna dlakavost kod zena', 'is_pillar': False,
             'slug': 'hirzutizam-prekomjerna-dlakavost-zene'},
            {'keyword': 'Koza u trudnoci: promjene i njega', 'is_pillar': False,
             'slug': 'koza-trudnoca-promjene-njega'},
            {'keyword': 'Kosa u menopauzi: sto ocekivati', 'is_pillar': False,
             'slug': 'kosa-menopauza-promjene'},
            {'keyword': 'Vitamin za kosu i nokte: biotin i drugi', 'is_pillar': False,
             'slug': 'vitamin-kosa-nokti-biotin'},
            {'keyword': 'Koza u menstruaciji: zasto se pojavljuju bubuljice', 'is_pillar': False,
             'slug': 'koza-menstruacija-bubuljice-hormoni'},
            {'keyword': 'SPF i zensko zdravlje koze: zasto je vazno', 'is_pillar': False,
             'slug': 'spf-zastita-koza-zene'},
            {'keyword': 'Retinoidi i zenska koza: bezbjedna upotreba', 'is_pillar': False,
             'slug': 'retinoidi-zenska-koza-upotreba'},
            {'keyword': 'Endometrioza i koza: manje poznata veza', 'is_pillar': False,
             'slug': 'endometrioza-koza-veza'},
            {'keyword': 'Alopecija areata kod zena: uzroci i lijecenje', 'is_pillar': False,
             'slug': 'alopecija-areata-zene'},
            {'keyword': 'Seboreicni dermatitis kod zena', 'is_pillar': False,
             'slug': 'seboreicni-dermatitis-zene'},
            {'keyword': 'Kolagen i elastin: kako sacuvati mladu kozu', 'is_pillar': False,
             'slug': 'kolagen-elastin-mlada-koza'},
            {'keyword': 'Masna koza i hormoni: kako kontrolisati', 'is_pillar': False,
             'slug': 'masna-koza-hormoni-kontrola'},
            {'keyword': 'Kosa i ishrana: hrana za jacu i zdraviju kosu', 'is_pillar': False,
             'slug': 'kosa-ishrana-hrana-zdravija'},
            {'keyword': 'Teleangiektazije i rosacea kod zena: uzroci', 'is_pillar': False,
             'slug': 'rosacea-teleangiektazije-zene'},
            {'keyword': 'Njega koze u razlicitim fazama ciklusa', 'is_pillar': False,
             'slug': 'njega-koze-faze-ciklusa'},
        ],
    },

    # --- CLUSTER 9: Fitness i tjelovjezbanje ---
    {
        'cluster': 'fitness-zene',
        'posts': [
            {'keyword': 'Fitness za zene: vodic kroz vjezbanje i zenski ciklus', 'is_pillar': True,
             'slug': 'fitness-zene-vodic-ciklus'},
            {'keyword': 'Vjezbanje u razlicitim fazama menstrualnog ciklusa', 'is_pillar': False,
             'slug': 'vjezbanje-faze-menstrualnog-ciklusa'},
            {'keyword': 'Yoga za zensko zdravlje: posebne poze za hormone', 'is_pillar': False,
             'slug': 'yoga-zensko-zdravlje-hormoni'},
            {'keyword': 'Trening snage za zene: prednosti i mitovi', 'is_pillar': False,
             'slug': 'trening-snage-zene-prednosti'},
            {'keyword': 'Kardio vjezbanje i zenski hormoni', 'is_pillar': False,
             'slug': 'kardio-zenski-hormoni'},
            {'keyword': 'Vjezbanje za smanjenje boli u menstruaciji', 'is_pillar': False,
             'slug': 'vjezbanje-smanjenje-menstrualni-bol'},
            {'keyword': 'Prevjezbavanje i gubitak menstruacije: FHA', 'is_pillar': False,
             'slug': 'prevjezbavanje-gubitak-menstruacije-fha'},
            {'keyword': 'Pilates za zensku zdjelicu i core', 'is_pillar': False,
             'slug': 'pilates-zenska-zdjelica-core'},
            {'keyword': 'Hodanje i zensko zdravlje: koliko je dovoljno', 'is_pillar': False,
             'slug': 'hodanje-zensko-zdravlje-koraci'},
            {'keyword': 'Vjezbe za dno zdjelice: Kegelove vjezbe', 'is_pillar': False,
             'slug': 'vjezbe-dno-zdjelice-kegel'},
        ],
    },

    # --- CLUSTER 10: Medicinski testovi ---
    {
        'cluster': 'medicinski-testovi',
        'posts': [
            {'keyword': 'Medicinski testovi za zensko zdravlje: kompletan vodic', 'is_pillar': True,
             'slug': 'medicinski-testovi-zensko-zdravlje'},
            {'keyword': 'Hormonski panel za zene: koji testovi i kada', 'is_pillar': False,
             'slug': 'hormonski-panel-zene-testovi'},
            {'keyword': 'AMH test: rezerva jajnika i plodnost', 'is_pillar': False,
             'slug': 'amh-test-rezerva-jajnika'},
            {'keyword': 'Testovi stitnjace: TSH, T3, T4 i anti-tireoidna antitijela', 'is_pillar': False,
             'slug': 'testovi-stitnjace-tsh-t3-t4'},
            {'keyword': 'Krvna slika za zene: sto znace rezultati', 'is_pillar': False,
             'slug': 'krvna-slika-zene-rezultati'},
            {'keyword': 'Insulinska rezistencija: HOMA-IR test i rezultati', 'is_pillar': False,
             'slug': 'insulinska-rezistencija-homa-ir-test'},
            {'keyword': 'Vitamin D test: kada napraviti i sto znace vrijednosti', 'is_pillar': False,
             'slug': 'vitamin-d-test-vrijednosti'},
            {'keyword': 'Anemija kod zena: CBC i feritin testovi', 'is_pillar': False,
             'slug': 'anemija-zene-cbc-feritin'},
            {'keyword': 'Trigliceridi i holesterol kod zena', 'is_pillar': False,
             'slug': 'trigliceridi-holesterol-zene'},
            {'keyword': 'STI testovi za zene: kada i kako', 'is_pillar': False,
             'slug': 'sti-testovi-zene-kada-kako'},
        ],
    },
]

# Flat list for easy iteration
ALL_POSTS = []
for cluster_data in CLUSTERS:
    for post in cluster_data['posts']:
        post['cluster'] = cluster_data['cluster']
        ALL_POSTS.append(post)

TOTAL_POSTS = len(ALL_POSTS)  # Should be 200

# Lookup by cluster: returns the pillar for each cluster
PILLAR_BY_CLUSTER = {}
for cluster_data in CLUSTERS:
    for post in cluster_data['posts']:
        if post['is_pillar']:
            PILLAR_BY_CLUSTER[cluster_data['cluster']] = post
            break
